#!/bin/bash

# Guide d'utilisation des outils d'entraînement Garmin

echo "💪 Guide des outils d'entraînement Garmin MCP"
echo "============================================"
echo ""
echo "📋 Entraînements disponibles:"
echo ""
echo "🏋️ 1. PUSH COMPLET (push_complete_final.py)"
echo "   • Pectoraux, épaules, triceps"
echo "   • 5 exercices principaux + superset"
echo "   • Durée: 75-90 minutes"
echo "   • Usage: python push_complete_final.py"
echo ""
echo "🏋️ 2. PUSH SCULPT FORMAT (push_sculpt_format.py)"
echo "   • Version optimisée pour Sculpt"
echo "   • Structure compatible montre"
echo "   • Durée: 60-75 minutes"
echo "   • Usage: python push_sculpt_format.py"
echo ""
echo "🎯 3. REACHER - DOS BICEPS (reacher_dos_biceps.py)"
echo "   • Dos, biceps, arrière d'épaules"
echo "   • 9 exercices complets"
echo "   • Durée: 60-75 minutes"
echo "   • Usage: python reacher_dos_biceps.py"
echo ""
echo "🦵 4. LEGS + ABS RITCHSON (legs_abs_ritchson.py)"
echo "   • Jambes et abdos intensifs"
echo "   • 300+ répétitions core"
echo "   • Durée: 70-80 minutes"
echo "   • Usage: python legs_abs_ritchson.py"
echo ""
echo "🏗️ 5. CRÉATEUR PUSH COMPLET (create_complete_push_workout.py)"
echo "   • Générateur d'entraînement push"
echo "   • Guidage étape par étape"
echo "   • Durée: 75-90 minutes"
echo "   • Usage: python create_complete_push_workout.py"
echo ""
echo "🔧 Pré-requis:"
echo "   1. Fichier .env configuré avec vos identifiants Garmin"
echo "   2. Tokens Garmin générés (python example.py)"
echo "   3. Connexion internet active"
echo ""
echo "💡 Conseils d'utilisation:"
echo "   • Exécutez un seul entraînement à la fois"
echo "   • Attendez 30 secondes entre chaque upload"
echo "   • Synchronisez votre montre après création"
echo "   • Cherchez l'entraînement par son nom sur la montre"
echo ""
echo "🎯 Formats compatibles:"
echo "   • Montres Garmin avec support HIIT"
echo "   • Application Garmin Connect"
echo "   • Synchronisation automatique"
echo ""
echo "🆘 En cas de problème:"
echo "   • Vérifiez votre connexion internet"
echo "   • Attendez 15-30 minutes entre les tentatives"
echo "   • Regénérez les tokens si nécessaire"
echo "   • Contactez le support si les erreurs persistent"
echo ""
echo "🚀 Prêt à créer vos entraînements Garmin !"